/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fox.gltf')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    // actions.Run.play()
    // actions.Survey.play()
    actions.Walk.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.fox.geometry} material={materials.fox_material} skeleton={nodes.fox.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fox.gltf')
